const currencies={
    "USD": "United States Dollar",
    "EUR": "Euro",
    "JPY": "Japanese Yen",
    "GBP": "British Pound Sterling",
    "AUD": "Australian Dollar",
    "CAD": "Canadian Dollar",
    "CHF": "Swiss Franc",
    "CNY": "Chinese Yuan",
    "SEK": "Swedish Krona",
    "NZD": "New Zealand Dollar",
    "MXN": "Mexican Peso",
    "SGD": "Singapore Dollar",
    "HKD": "Hong Kong Dollar",
    "NOK": "Norwegian Krone",
    "KRW": "South Korean Won",
    "TRY": "Turkish Lira",
    "RUB": "Russian Ruble",
    "INR": "Indian Rupee",
    "BRL": "Brazilian Real",
    "ZAR": "South African Rand",
    "SAR": "Saudi Riyal",
    "DKK": "Danish Krone",
    "PLN": "Polish Zloty",
    "THB": "Thai Baht",
    "ILS": "Israeli New Shekel",
    "CLP": "Chilean Peso",
    "PHP": "Philippine Peso",
    "AED": "United Arab Emirates Dirham",
    "COP": "Colombian Peso",
    "MYR": "Malaysian Ringgit",
    "PEN": "Peruvian Nuevo Sol",
    "ARS": "Argentine Peso",
    "VND": "Vietnamese Dong",
    "HUF": "Hungarian Forint",
    "CZK": "Czech Koruna",
    "RON": "Romanian Leu",
    "SEK": "Swedish Krona",
    "ISK": "Icelandic Króna",
    "BDT": "Bangladeshi Taka",
    "JMD": "Jamaican Dollar",
    "XOF": "West African CFA Franc",
    "XAF": "Central African CFA Franc",
    "XCD": "East Caribbean Dollar",
    "DOP": "Dominican Peso",
    "CRC": "Costa Rican Colón",
    "PYG": "Paraguayan Guarani",
    "GTQ": "Guatemalan Quetzal",
    "NIO": "Nicaraguan Córdoba",
    "CUP": "Cuban Peso",
    "MOP": "Macanese Pataca",
    "TWD": "New Taiwan Dollar",
    "SYP": "Syrian Pound",
    "LKR": "Sri Lankan Rupee",
    "LAK": "Lao Kip",
    "MUR": "Mauritian Rupee",
    "BAM": "Bosnia and Herzegovina Convertible Mark",
    "HRK": "Croatian Kuna",
    "MKD": "Macedonian Denar",
    "MDL": "Moldovan Leu",
    "BHD": "Bahraini Dinar",
    "KWD": "Kuwaiti Dinar",
    "OMR": "Omani Rial",
    "JOD": "Jordanian Dinar",
    "TND": "Tunisian Dinar",
    "LYD": "Libyan Dinar",
    "MGA": "Malagasy Ariary",
    "RWF": "Rwandan Franc",
    "ETB": "Ethiopian Birr",
    "KES": "Kenyan Shilling",
    "TZS": "Tanzanian Shilling",
    "UGX": "Ugandan Shilling",
    "XPF": "CFP Franc",
    "MNT": "Mongolian Tugrik",
    "KZT": "Kazakhstani Tenge",
    "GHS": "Ghanaian Cedi",
    "SLL": "Sierra Leonean Leone",
    "NGN": "Nigerian Naira",
    "TMT": "Turkmenistani Manat",
    "AMD": "Armenian Dram",
    "BND": "Brunei Dollar",
    "RSD": "Serbian Dinar",
    "BWP": "Botswana Pula",
    "BND": "Brunei Dollar",
    "MZN": "Mozambican Metical",
    "ETB": "Ethiopian Birr",
    "XOF": "West African CFA Franc",
    "SBD": "Solomon Islands Dollar",
    "PGK": "Papua New Guinean Kina",
    "VUV": "Vanuatu Vatu",
    "YER": "Yemeni Rial",
    "SBD": "Solomon Islands Dollar",
    "XPF": "CFP Franc",
    "KGS": "Kyrgystani Som",
    "PAB": "Panamanian Balboa",
    "BND": "Brunei Dollar",
    "XAF": "Central African CFA Franc",
    "HNL": "Honduran Lempira",
    "KYD": "Cayman Islands Dollar",
    "NAD": "Namibian Dollar",
    "SRD": "Surinamese Dollar",
    "CVE": "Cape Verdean Escudo",
    "MOP": "Macanese Pataca",
    "SLL": "Sierra Leonean Leone",
    "KWD": "Kuwaiti Dinar",
    "SDG": "Sudanese Pound",
    "MNT": "Mongolian Tugrik",
    "BIF": "Burundian Franc",
    "AFN": "Afghan Afghani",
    "NAD": "Namibian Dollar",
    "JEP": "Jersey Pound",
    "SYP": "Syrian Pound",
    "LKR": "Sri Lankan Rupee",
    "DZD": "Algerian Dinar",
    "GMD": "Gambian Dalasi",
    "BWP": "Botswana Pula",
    "KPW": "North Korean Won"
  }
  